package com.example.nonprofitapp;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;

import android.widget.Button;
import android.widget.TextView;

import com.example.nonprofitapp.ui.login.LoginActivity;
import android.widget.EditText;


import android.widget.EditText;
import android.content.Intent;


/*
 * Hello Pro team! This is a basic hello world app generated by Android Studio.
 *
 * Check out /res/layout/activity_main.xml for the GUI. Double clicking the text should let you
 * edit the TextView object.
 */

public class MainActivity extends AppCompatActivity implements View.OnClickListener {
    public static final String LOGIN_TYPE = "LOGIN_TYPE"; // Sent with intent as a label
    public static final String VOLUNTEER = "VOLUNTEER";
    public static final String CUSTOMER = "CUSTOMER";

    public static final String SELECTED_BAG = "com.example.nonprofitapp.BAG";
    public static final String YEAR = "com.example.nonprofitapp.YEAR";
    public static final String MONTH = "com.example.nonprofitapp.MONTH";
    public static final String DAY = "com.example.nonprofitapp.DAY";
    public static final String HOUR = "com.example.nonprofitapp.HOUR";
    public static final String MINUTE = "com.example.nonprofitapp.MINUTE";
    public static final String FOOD_BANK_BUTTON = "com.example.nonprofitapp.FOOD_BANK_BUTTON"; // For food bank selection

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Button customerSignIn = (Button) findViewById(R.id.customer_sign_in);
        customerSignIn.setOnClickListener(this);
        TextView volunteerSignIn = (TextView) findViewById(R.id.volunteer_sign_in);
        volunteerSignIn.setOnClickListener(this);
    }

    /*
     * Handles both the customer sign in and volunteer sign in buttons.
     */
    @Override
    public void onClick(View view) {
        switch (view.getId()) {
            case R.id.customer_sign_in:
                customerClick();
                break;
            case R.id.volunteer_sign_in:
                volunteerClick();
                break;
        }
    }

    public void customerClick() {
        Intent launch = new Intent(this, LoginActivity.class);
        launch.putExtra(LOGIN_TYPE, CUSTOMER);
        startActivity(launch);
    }

    public void volunteerClick() {
        Intent launch = new Intent(this, LoginActivity.class);
        launch.putExtra(LOGIN_TYPE, VOLUNTEER);
        startActivity(launch);
    }

    /** Called after user logs in as a customer and selects a food bank */
    public void selectGroceryBag(View view) {
        Intent intent = new Intent(this, GroceryBagSelectionActivity.class);
        startActivity(intent);
    }

    public void sendMessageFoodbank(View view) {
        Intent intent = new Intent(this, Foodbank_Selection_Page.class);
        startActivity(intent);
    }



    public void sendMessageWindow(View view) {
        //do something
        Intent intent = new Intent(this, Window_Display.class);
        startActivity(intent);

    }
}
