package com.example.nonprofitapp;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import com.example.nonprofitapp.ui.login.LoginActivity;

/*
 * Hello Pro team! This is a basic hello world app generated by Android Studio.
 *
 * Check out /res/layout/activity_main.xml for the GUI. Double clicking the text should let you
 * edit the TextView object.
 */
public class MainActivity extends AppCompatActivity implements View.OnClickListener {
    public static final String LOGIN_TYPE = "LOGIN_TYPE"; // Sent with intent as a label
    public static final String VOLUNTEER = "VOLUNTEER";
    public static final String CUSTOMER = "CUSTOMER";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Button customerSignIn = (Button) findViewById(R.id.customer_sign_in);
        customerSignIn.setOnClickListener(this);
        TextView volunteerSignIn = (TextView) findViewById(R.id.volunteer_sign_in);
        volunteerSignIn.setOnClickListener(this);
    }

    /*
     * Handles both the customer sign in and volunteer sign in buttons.
     */
    @Override
    public void onClick(View view) {
        switch (view.getId()) {
            case R.id.customer_sign_in:
                customerClick();
                break;
            case R.id.volunteer_sign_in:
                volunteerClick();
                break;
        }
    }

    public void customerClick() {
        Intent launch = new Intent(this, LoginActivity.class);
        launch.putExtra(LOGIN_TYPE, CUSTOMER);
        startActivity(launch);
    }

    public void volunteerClick() {
        Intent launch = new Intent(this, LoginActivity.class);
        launch.putExtra(LOGIN_TYPE, VOLUNTEER);
        startActivity(launch);
    }
}
