package com.example.nonprofitapp;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.EditText;

/*
 * Hello Pro team! This is a basic hello world app generated by Android Studio.
 *
 * Check out /res/layout/activity_main.xml for the GUI. Double clicking the text should let you
 * edit the TextView object.
 */
public class MainActivity extends AppCompatActivity {
    public static final String SELECTED_BAG = "com.example.nonprofitapp.BAG";
    public static final String YEAR = "com.example.nonprofitapp.YEAR";
    public static final String MONTH = "com.example.nonprofitapp.MONTH";
    public static final String DAY = "com.example.nonprofitapp.DAY";
    public static final String HOUR = "com.example.nonprofitapp.HOUR";
    public static final String MINUTE = "com.example.nonprofitapp.MINUTE";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    /** Called after user logs in as a customer and selects a food bank */
    public void selectGroceryBag(View view) {
        Intent intent = new Intent(this, GroceryBagSelectionActivity.class);
        startActivity(intent);
    }
}
